#!/bin/bash

# =================================================================================================
# RaspPunzel Test Configuration (Vagrant)
# =================================================================================================

# Ligolo-ng configuration
LIGOLO_VERSION="v0.8"
LIGOLO_PROXY_HOST="10.0.2.2"  # Host machine (Vagrant NAT gateway)
LIGOLO_PROXY_PORT="11601"
LIGOLO_IGNORE_CERT="true"
LIGOLO_RETRY_DELAY="10"
LIGOLO_AUTO_RESTART="true"

# Network interfaces (auto-detected)
MAC_ETH0="08:00:27:b6:b2:08"
MAC_WLAN0="00:00:00:00:00:00"  # Not used in VM
WLAN_INTERFACE_ADMIN="none"    # No WiFi in VM
WLAN_INTERFACE_ALFA_NEH="none"
WLAN_INTERFACE_ALFA_ACH="none"

# WiFi credentials (not used in VM)
WIFI_SSID="NotUsed"
WIFI_PASSPHRASE="NotUsed"

# Admin AP (disabled in VM - no WiFi adapter)
ADMIN_AP_SSID="PIVOT_ADMIN_TEST"
ADMIN_AP_PASSPHRASE="Test123456!"
ADMIN_AP_HIDDEN="0"
ADMIN_AP_CHANNEL="6"
ADMIN_AP_IP="10.0.0.1"
ADMIN_AP_NETMASK="255.255.255.0"
ADMIN_AP_NETWORK="10.0.0.0/24"
ADMIN_AP_DHCP_START="10.0.0.2"
ADMIN_AP_DHCP_END="10.0.0.30"
ADMIN_AP_DHCP_LEASE="12h"
ADMIN_AP_DNS_PRIMARY="8.8.8.8"
ADMIN_AP_DNS_SECONDARY="8.8.4.4"

# SSH configuration
SSH_PORT="22"
SSH_ROOT_LOGIN="yes"
SSH_PASSWORD_AUTH="yes"

# Web dashboard
ENABLE_WEB_DASHBOARD="true"
WEB_PORT="5000"
WEB_USERNAME="admin"
WEB_PASSWORD="rasppunzel"

# System configuration
HOSTNAME="rasppunzel-test"
TIMEZONE="UTC"
NTP_SERVERS="pool.ntp.org"
IP_FORWARDING="true"

# Security settings
ENABLE_FIREWALL="false"  # Disabled for testing
ENABLE_FAIL2BAN="false"
SSH_ALLOWED_IPS="any"

# Logging
LOG_LEVEL="info"
LOG_RETENTION_DAYS="7"

# Advanced options
LIGOLO_BIND_ADDR="0.0.0.0"
TCP_CONGESTION_CONTROL="cubic"
MAX_CONNECTIONS="1000"

# Export all variables
export LIGOLO_VERSION LIGOLO_PROXY_HOST LIGOLO_PROXY_PORT
export LIGOLO_IGNORE_CERT LIGOLO_RETRY_DELAY LIGOLO_AUTO_RESTART
export MAC_ETH0 MAC_WLAN0
export WLAN_INTERFACE_ADMIN WLAN_INTERFACE_ALFA_NEH WLAN_INTERFACE_ALFA_ACH
export WIFI_SSID WIFI_PASSPHRASE
export ADMIN_AP_SSID ADMIN_AP_PASSPHRASE ADMIN_AP_HIDDEN ADMIN_AP_CHANNEL
export ADMIN_AP_IP ADMIN_AP_NETMASK ADMIN_AP_NETWORK
export ADMIN_AP_DHCP_START ADMIN_AP_DHCP_END ADMIN_AP_DHCP_LEASE
export ADMIN_AP_DNS_PRIMARY ADMIN_AP_DNS_SECONDARY
export SSH_PORT SSH_ROOT_LOGIN SSH_PASSWORD_AUTH
export ENABLE_WEB_DASHBOARD WEB_PORT WEB_USERNAME WEB_PASSWORD
export HOSTNAME TIMEZONE NTP_SERVERS IP_FORWARDING
export ENABLE_FIREWALL ENABLE_FAIL2BAN SSH_ALLOWED_IPS
export LOG_LEVEL LOG_RETENTION_DAYS
export LIGOLO_BIND_ADDR TCP_CONGESTION_CONTROL MAX_CONNECTIONS
